---
- hosts: "{{ Ipaddresse }}"
  remote_user: "{{ username }}"
  become: yes
  vars_files:
    - vars/authentication.yml

  tasks:
  - name: Update Ubuntu
    command: apt update

  - name: Create a user
    user:
      name: "{{ user }}"
      state: present
      groups: sudo
      append: yes
      password: "{{ mypassword | password_hash('sha512')  }}"

  - name: Add user to the sudoers
    copy:
      dest: '/etc/sudoers.d/"{{ user }}"'
      content: '"{{ user }}" ALL=(ALL) NOPASSWD: ALL'

  - name: Copy the ssh-key
    authorized_key:
      user: "{{ user }}"
      key: "{{ lookup('file', '/home/devasc/.ssh/id_rsa.pub') }}"
      state: present

  - name: Install docker packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: Add user to the docker group 
    user:
      name: "{{ user }}"
      group: docker
      append: yes

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.26.0-rc4/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      checksum: sha256:3ad2031c7daae160b8987538a60261475b3e17dfccf6fb96c1ae67d23afecdb8
      mode: u+x,g+x

  - name: Start docker
    service:
      name: docker
      state: started
      enabled: true

  - name: Intall docker SDK
    command: pip install docker

  - name: Create a network for reverse-proxy
    command: docker network create nginx-proxy
    

  - name: Create /home/reverse-proxy directory
    file:
      path: /home/reverse-proxy/
      state: directory
  
  - name: Copy the docker-compose file
    copy:
      src: ./reverse-proxy/docker-compose.yml
      dest: /home/reverse-proxy/docker-compose.yml
      mode: u+x

  - name: Run docker-compose to set up the nginx reverse proxy
    shell: docker-compose up -d
    args:
      chdir: /home/reverse-proxy/
 
