---
- hosts: "{{ IPaddresse }}"
  remote_user: "{{ user }}"
  become: yes
  vars_files:
    - vars/authentication.yml

  tasks:
  - name: Restart the service of the client
    shell: docker-compose up -d
    args:
      chdir: "/home/services/{{ servicename }}/clients/{{ clientname }}/"
